name: ABZ test

on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, tokenizer, xml

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Optimize clear
        run: php artisan optimize:clear

      - name: Generate storage link
        run: php artisan storage:link


